config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  resources :contacts
  get 'sessions/new'

  resources :tweets do
    collection do
      post :confirm
    end
  end

  resources :favorites, only: [:create, :destroy]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user

  validates :content, presence: true
  validates :content, length: { in: 1..140 }

  mount_uploader :image, ImageUploader
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action:current_user_check, only:[:new, :edit, :destroy]
  before_action:set_tweet, only:[:edit, :update, :destroy]
  before_action:get_tweet_list, only:[:index, :confirm, :create]

  def index

    # ツイート投稿保持
    if params[:back]
      @tweet = Tweet.new(tweet_params)
    else
      @tweet = Tweet.new
    end

  end

  #編集画面
  def edit
  end

  #編集処理
  def update
    if @tweet.update(tweet_params)
      #成功の場合
      redirect_to tweets_path, notice: 'つぶやきの編集が完了しました'
    else
      #失敗の場合
      render 'edit'
    end
  end

  #削除処理
  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: 'つぶやきの削除が完了しました'
  end

  #新規作成処理
  def create

    @tweet = Tweet.new(tweet_params)

    unless params[:cache].nil?
      # 画像ファイル設定処理があるなら
      @tweet.image.retrieve_from_cache! params[:cache][:image]
      @tweet.save!
    end

    if @tweet.save
      redirect_to tweets_path, notice: '新規のつぶやきが完了しました'

    else

      render confirm_tweets_path
    end
  end

  def confirm
    @tweet = Tweet.new(tweet_params)
    render:index if @tweet.invalid?
  end

  # def show
  #
  # end

private
  def tweet_params
    # raise
    params.require(:tweet).permit(:content, :user_id, :image)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def get_tweet_list
    @list = Tweet.all
  end

  # ログインしていないのに入る
  def current_user_check
    if !current_user
      redirect_to tweets_path, notice: 'ログインしていない'
    end
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_error.html.erb
<% if @tweet.errors.any? %>
  <div id="error_explanation">
    <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>

    <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%=msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/tweets/_form.html.erb
<div class="container">
  <div class="intro-text">

    <div class="col-lg-4"></div>
    <div class="col-lg-4" style="text-align:center;">
      <%= form_with(model:@tweet, local:true) do |form| %>
        <%= form.hidden_field :content %>
        <%= form.hidden_field :user_id, :value => current_user.id  %>
        <%= form.text_area :content, :class=>"form-control"  %>
        <!-- 確認画面から新規作成画面に戻った時に情報を保持するための記述 -->

        <% unless @tweet.image.url.nil? then %>
          <%= image_tag(@tweet.image.url) %>
          <%= hidden_field_tag :"cache[image]",@tweet.image.cache_name %>
        <% end %>
        <br />

        <%= render 'error' %>

        <p><%= form.submit "つぶやく",:class=>"btn btn-primary" %></p>
      <% end %>

      <%= form_with(model:@tweet, url:tweets_path, local:true, method:'get') do |form| %>
        <%= form.hidden_field :content %>
        <p><%= form.submit "戻る",name:'back',:class=>"btn btn-primary" %></p>
      <% end %>
    </div>
    <div class="col-lg-4"></div>
  </div>
</div>

app/views/tweets/confirm.html.erb
<h3 align="center">以下の内容で、つぶやきますよ？よろしいですか？</h3>

<%= render 'form' %>

app/views/tweets/edit.html.erb
<h3 align="center">つぶやき内容を編集しますよ？</h3>

<%= render 'form' %>

app/views/tweets/index.html.erb
<!-- Header -->
<header class="masthead">
  <div class="container">
    <div class="intro-text">
      <% if logged_in? %>
        <!-- ログインしている場合 -->

        <div class="intro-heading text-uppercase">いまどうしてる？</div>

        <div class="col-lg-4"></div>
        <div class="col-lg-4">
          <%= form_with(model: @tweet, local: true, url:confirm_tweets_path) do |form| %>
            <p><%= form.text_area :content, :class=>"form-control" %></p>
            <p>
              <%= form.file_field :image, id: :tweet_image %>
              <!-- 確認画面から新規作成画面に戻った時に情報を保持するための記述 -->
              <%= form.hidden_field :image_cache %>
            </p>
            <p><%= form.submit :"つぶやく", :class=>"btn btn-primary" %></p>
            <%= form.hidden_field :user_id, :value => current_user.id %>
            <%= render 'error' %>
          <% end %>
        </div>
        <div class="col-lg-4"></div>
      <% else %>
        <!-- # ログインしていない場合 -->
        <p class="intro-heading text-uppercase">ログインしてください</p>
        <p class="col-lg-12"><%= link_to 'ログイン画面', new_session_path %></p>

      <% end %>

    </div>
  </div>
</header>


<!-- twitter_list -->
<section id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase">みんなのつぶやき</h2>
      </div>
    </div>

    <% if @list.count == 0 %>
      <!-- ０件だったら、投稿無い旨表示する -->
      <p>まだツイートがありません。新規につぶやいてください</p>

    <% else %>
      <div class="row">
        <% @list.reverse_each do |list| %>
          <div class="col-lg-12" style="border: inset 0px #ff0000;">
            <ul>
              <li>
                <h3><%= list.content %></h4>
                <% unless list.image.url.nil? then %>
                  <p><%= image_tag(list.image.url, :size =>"200") %></p>
                <% end %>
                <p><i><%= list.created_at %></i>  | <%= link_to '問い合わせ', new_contact_path(user_id: list.user_id), style: 'color:red' %></p>


                <% if logged_in? %>
                  <!-- ログインしている場合のみお気に入り選択 -->

                  <!-- お気に入りツイート取得 -->
                  <% @favorite = current_user.favorites.find_by(tweet_id: list.id) %>

                  <!-- お気に入り選択 -->
                  <% if @favorite.present? %>
                    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
                  <% else %>
                    <%= link_to 'お気に入りする', favorites_path(tweet_id: list.id), method: :post, class: 'btn btn-primary' %>
                  <% end %>
                <% end %>

                <!-- 自分のIDの場合のみ表示する -->
                <% if !current_user.nil? && list.user_id == current_user.id %>
                  <div class="tweet-button-field">
                    <%= link_to '編集', edit_tweet_path(list.id), class: 'btn btn-info' %> |
                    <%= link_to '削除', list, method: :delete, data: { confirm: 'このつぶやきを削除しますか?' }, class: 'btn btn-danger' %>
                  </div>
                <% end %>

              </li>
            </ul>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</section>


<!-- Bootstrap core JavaScript -->
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Plugin JavaScript -->
<script src="vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Contact form JavaScript -->
<script src="js/jqBootstrapValidation.js"></script>
<script src="js/contact_me.js"></script>

<!-- Custom scripts for this template -->
<script src="js/agency.min.js"></script>